imports:
    - { resource: step_types.yml }

monolog:
    channels: [payment]
    handlers:
        payment_log:
            type: stream
            path: "%kernel.logs_dir%/payment_%kernel.environment%.log"
            channels: [payment]

