---
idci_payment_paymentgateway:
    resource: IDCI\Bundle\PaymentBundle\Controller\PaymentGatewayController

idci_payment_stripepaymentgateway:
    resource: IDCI\Bundle\PaymentBundle\Controller\StripePaymentGatewayController
