---
idci_payment_test_paymentgatewayfront:
    resource: IDCI\Bundle\PaymentBundle\Controller\Test\PaymentGatewayFrontTestController

idci_payment_paymentgateway:
    resource: IDCI\Bundle\PaymentBundle\Controller\PaymentGatewayController
