---
idci_payment_frontpayment:
    resource: IDCI\Bundle\PaymentBundle\Controller\FrontPaymentController

idci_payment_backendpayment:
    resource: IDCI\Bundle\PaymentBundle\Controller\BackendPaymentController
