---
services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    IDCI\Bundle\PaymentBundle\:
        resource: '../../*'
        exclude: '../../{Entity,Repository,Tests}'

    # Payment Gateways

    IDCI\Bundle\PaymentBundle\Gateway\StripePaymentGateway:
        tags:
            - { name: idci_payment.gateways, alias: stripe }

    IDCI\Bundle\PaymentBundle\Gateway\PaypalPaymentGateway:
        tags:
            - { name: idci_payment.gateways, alias: paypal }

    IDCI\Bundle\PaymentBundle\Gateway\AtosSipsSealPaymentGateway:
        tags:
            - { name: idci_payment.gateways, alias: atos_sips_seal }
