---
services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    IDCI\Bundle\PaymentBundle\:
        resource: '../../*'
        exclude: '../../{Entity,Repository,Tests}'

    IDCI\Bundle\PaymentBundle\Gateway\StripePaymentGateway:
        tags:
            - { name: idci_payment.gateways, alias: stripe }
