---
services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    IDCI\Bundle\PaymentBundle\:
        resource: '../../*'
        exclude: '../../{Entity,Repository,Tests}'

    IDCI\Bundle\PaymentBundle\Gateway\PaymentGatewayFactory:
        arguments:
            $paymentGatewayList: '%idci_payment.gateways%'
