---
services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    IDCI\Bundle\PaymentBundle\:
        resource: '../../*'
        exclude: '../../{Entity,Repository,Tests}'

    # Payment Gateways

    IDCI\Bundle\PaymentBundle\Gateway\StripePaymentGateway:
        tags:
            - { name: idci_payment.gateways, alias: stripe }

    IDCI\Bundle\PaymentBundle\Gateway\PaypalPaymentGateway:
        tags:
            - { name: idci_payment.gateways, alias: paypal }

    IDCI\Bundle\PaymentBundle\Gateway\MercanetAtosSipsSealPaymentGateway:
        arguments:
            $serverUrl: '%idci_payment.mercanet.server_url%'
        tags:
            - { name: idci_payment.gateways, alias: mercanet_atos_sips_seal }

    IDCI\Bundle\PaymentBundle\Gateway\PayboxPaymentGateway:
        tags:
            - { name: idci_payment.gateways, alias: paybox }
