idci_payment:

    templates:

        step:

            failed: '@IDCIPaymentBundle/Resources/views/PaymentStep/failed.html.twig'
            success: '@IDCIPaymentBundle/Resources/views/PaymentStep/success.html.twig'
            initialize: '@IDCIPaymentBundle/Resources/views/PaymentStep/initialize.html.twig'
            pending: '@IDCIPaymentBundle/Resources/views/PaymentStep/pending.html.twig'
