idci_payment:

    templates:

        step:

            failed: '@IDCIPaymentBundle/Resources/views/PaymentStep/failed.html.twig'
            approved: '@IDCIPaymentBundle/Resources/views/PaymentStep/approved.html.twig'
            created: '@IDCIPaymentBundle/Resources/views/PaymentStep/created.html.twig'
            pending: '@IDCIPaymentBundle/Resources/views/PaymentStep/pending.html.twig'
